vein-miner-categories:
  - ==: VeinMinerCategory
    name: Logs
    icon: OAK_LOG
    materials:
      - OAK_LOG
      - SPRUCE_LOG
      - BIRCH_LOG
      - JUNGLE_LOG
      - ACACIA_LOG
      - DARK_OAK_LOG
      - MANGROVE_LOG
      - CHERRY_LOG
  - ==: VeinMinerCategory
    name: Ores
    icon: IRON_ORE
    materials:
      - COAL_ORE
      - IRON_ORE
      - COPPER_ORE
      - GOLD_ORE
      - REDSTONE_ORE
      - EMERALD_ORE
      - LAPIS_ORE
      - DIAMOND_ORE
  - ==: VeinMinerCategory
    name: Deepslate Ores
    icon: DEEPSLATE_DIAMOND_ORE
    materials:
      - DEEPSLATE_COAL_ORE
      - DEEPSLATE_IRON_ORE
      - DEEPSLATE_COPPER_ORE
      - DEEPSLATE_GOLD_ORE
      - DEEPSLATE_REDSTONE_ORE
      - DEEPSLATE_EMERALD_ORE
      - DEEPSLATE_LAPIS_ORE
      - DEEPSLATE_DIAMOND_ORE
  - ==: VeinMinerCategory
    name: Nether Blocks
    icon: NETHERRACK
    materials:
      - NETHER_QUARTZ_ORE
      - NETHER_GOLD_ORE
      - ANCIENT_DEBRIS
      - NETHER_WART_BLOCK
      - GLOWSTONE
      - CRIMSON_STEM
      - WARPED_STEM
  - ==: VeinMinerCategory
    name: Stones
    icon: STONE
    materials:
      - GRANITE
      - DIORITE
      - ANDESITE
      - TUFF
      - CALCITE
  - ==: VeinMinerCategory
    name: Leaves
    icon: OAK_LEAVES
    materials:
      - OAK_LEAVES
      - SPRUCE_LEAVES
      - BIRCH_LEAVES
      - JUNGLE_LEAVES
      - ACACIA_LEAVES
      - DARK_OAK_LEAVES
      - MANGROVE_LEAVES
      - CHERRY_LEAVES
  - ==: VeinMinerCategory
    name: Etc
    icon: DIRT
    materials:
      - ICE
      - PACKED_ICE
      - BLUE_ICE
      - SNOW_BLOCK
      - SNOW
      - CLAY
  - ==: VeinMinerCategory
    name: Unstable
    icon: BARRIER
    materials:
      - SAND
      - GRAVEL
      - DEEPSLATE
      - STONE
      - DIRT
